public enum EnumAction
{
    Idle = 0,
    Run = 1,
    Roll = 2,
    Rush = 3,
    Stun = 4,
    Die = 5,
    Victory = 6,
    Attack = 10,
    PowerAttack = 11,
    Skill_1 = 20,
    Skill_2 = 21,
    Skill_3 = 22,
    HitAir = 30,
    KnockDown = 31,
    HitGround = 32,
    Hit = 33,
    Push = 34,
}
